version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for npm pull requests
    labels:
      - "dependencies"
      - "npm"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Security updates should be prioritized
    reviewers:
      - "cocart-headless/maintainers"
    versioning-strategy: auto
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions" 