version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cocart-network

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./test-plugins:/var/www/html/wp-content/plugins
      - ./test-setup:/var/www/html/wp-content/test-setup
    networks:
      - cocart-network

  wp-cli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10 &&
      wp core install --url=localhost:8080 --title="CoCart Test Site" --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email --path=/var/www/html &&
      wp plugin install woocommerce --activate --path=/var/www/html &&
      wp plugin install co-cart --activate --path=/var/www/html &&
      wp plugin install /var/www/html/wp-content/test-setup/plugins/cocart-products-api.zip --activate --path=/var/www/html &&
      wp theme install storefront --activate --path=/var/www/html &&
      wp wc shop_page_display --set --path=/var/www/html &&
      wp option update woocommerce_enable_guest_checkout "yes" --path=/var/www/html &&
      wp option update woocommerce_calc_taxes "yes" --path=/var/www/html &&
      wp option update woocommerce_currency "USD" --path=/var/www/html &&
      wp wc tax create --country="US" --state="*" --rate=6 --name="Sales Tax" --shipping=true --path=/var/www/html &&
      wp post create --post_type=product --post_status=publish --post_title="Test Product" --post_content="This is a test product" --post_excerpt="Test product description" --path=/var/www/html --porcelain > /tmp/product_id.txt &&
      wp wc product update $(cat /tmp/product_id.txt) --regular_price=19.99 --sku=TEST001 --manage_stock=true --stock_quantity=10 --path=/var/www/html &&
      echo "WordPress setup completed"
      '
    volumes:
      - ./test-plugins:/var/www/html/wp-content/plugins
      - ./test-setup:/var/www/html/wp-content/test-setup
    networks:
      - cocart-network

networks:
  cocart-network:

volumes:
  db_data: 